default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8
  username: root
  password: 



test:
  <<: *default
  database: solar_plan-test

development:
  <<: *default
  database: solar_plan-development



production:
  <<: *default
  database: solar_plan-production

